// Generates `icons.js` from the `@material-symbols/svg-400` package.
//
// The paths are never typed by hand: they are read out of the published icon set, so
// every glyph is the authentic Material Symbols Outlined one. `npm run build` runs
// this first, which also means a missing/renamed icon fails the build instead of
// silently rendering nothing.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));

// icon -> where it is used. Keep the comment: it is what makes a stale entry obvious.
const ICONS = {
    home: 'bottom bar: 首页',
    tune: 'bottom bar: 模式切换',
    more_horiz: 'bottom bar: 更多',
    refresh: 'top bar / log refresh',
    speed: 'home: work status card',
    memory: 'home: config card',
    devices: 'home: device card',
    package_2: 'home: module card',
    bolt: 'splash mark',
    check_circle: 'mode: current preset',
    radio_button_unchecked: 'mode: selectable preset',
    description: 'more: log',
    restart_alt: 'more: restart daemon',
    info: 'more: about',
    open_in_new: 'about: external links',
    error: 'error card',
    warning: 'warning state',
    arrow_back: 'top bar: exit the WebUI',
    layers: 'about: platform layer',
    language: 'more: language row',
    sync: 'restart in progress',
};

const out = new Map();
const missing = [];
for (const name of Object.keys(ICONS)) {
    try {
        const svg = readFileSync(
            join(here, '..', 'node_modules', '@material-symbols', 'svg-400', 'outlined', `${name}.svg`),
            'utf8',
        );
        const m = svg.match(/viewBox="([^"]+)"/);
        const d = svg.match(/<path d="([^"]+)"/);
        if (!m || !d) throw new Error('unexpected svg shape');
        out.set(name, { viewBox: m[1], d: d[1] });
    } catch (e) {
        missing.push(`${name} (${e.message})`);
    }
}
if (missing.length) {
    console.error('gen-icons: missing icons:', missing.join(', '));
    process.exit(1);
}

const body = [...out.entries()]
    .map(([name, { viewBox, d }]) => `    ${JSON.stringify(name)}: { viewBox: ${JSON.stringify(viewBox)}, d: ${JSON.stringify(d)} },`)
    .join('\n');

writeFileSync(
    join(here, '..', 'icons.js'),
    `// GENERATED by tools/gen-icons.mjs from @material-symbols/svg-400 — do not edit.\n` +
    `// ${out.size} Material Symbols Outlined glyphs.\n` +
    `export const ICONS = {\n${body}\n};\n\n` +
    `/** An inline <svg> string for \`name\`, sized by the surrounding CSS. */\n` +
    `export function icon(name) {\n` +
    `    const g = ICONS[name];\n` +
    `    if (!g) throw new Error('unknown icon: ' + name);\n` +
    `    return \`<svg xmlns="http://www.w3.org/2000/svg" viewBox="\${g.viewBox}" fill="currentColor"><path d="\${g.d}"/></svg>\`;\n` +
    `}\n`,
);
console.log(`gen-icons: wrote icons.js with ${out.size} icons`);
